🚧 Update to SDK 26.1.100
🏭 This commit was automatically generated by generate-modules-sdk script.

Fix of this commit will be marked as:
😀😀😀😀

Full error log:
Error:  asset 2022-7-25--1-32-20--d6a305ca-9757-4227-880e-18a36759d0bd/main.min.js 432 KiB [emitted] (name: main) 1 related asset
runtime modules 727 bytes 4 modules
asset modules 2.21 KiB
modules by path ./maps/ 2.05 KiB 30 modules
modules by path ./assets/ 168 bytes
modules by path ./assets/icons/*.png 84 bytes 2 modules
./assets/icons/cs.svg 42 bytes [built] [code generated]
./assets/map-tools/map-compass.svg 42 bytes [built] [code generated]
javascript modules 374 KiB
modules by path ./src/ 33.6 KiB 16 modules
modules by path ./node_modules/ 321 KiB 6 modules
modules by path ./maps/6-tray-modules/ 19.4 KiB
./maps/6-tray-modules/index.ts 279 bytes [built] [code generated]
./maps/6-tray-modules/world/europe/czechia-tray.module.tsx 19.1 KiB [built] [code generated]
./package.json 1.26 KiB [built] [code generated]

ERROR in C:\Users\me\work\collboard\map\src\modules\map-picking-tool.tsx
54:80-85
[tsl] ERROR in C:\Users\me\work\collboard\map\src\modules\map-picking-tool.tsx(54,81)
TS2339: Property 'point' does not exist on type 'Promise<{ point: Vector; normal: Vector; }>'.

webpack 5.35.1 compiled with 1 error in 12741 ms

Error:
at DevelopmentCompiler.<anonymous> (C:\Users\me\work\collboard\map\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:91:37)
at Generator.next (<anonymous>)
at C:\Users\me\work\collboard\map\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:8:71
at new Promise (<anonymous>)
at __awaiter (C:\Users\me\work\collboard\map\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:4:12)
at Watching.handler (C:\Users\me\work\collboard\map\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:85:72)
at C:\Users\me\work\collboard\map\node_modules\webpack\lib\Watching.js:204:9
at Hook.eval [as callAsync] (eval at create (C:\Users\me\work\collboard\map\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\me\work\collboard\map\node_modules\webpack\node_modules\tapable\lib\Hook.js:18:14)
at Watching._done (C:\Users\me\work\collboard\map\node_modules\webpack\lib\Watching.js:201:28)