🚧 Update to SDK 27.25.0
🏭 This commit was automatically generated by generate-modules-sdk script.

Fix of this commit will be marked as:
👨🏿🚴🏿‍♂️🤾🏿🤚

Full error log:
Error:  asset 2022-9-3--2-8-47--f3457ca5-dc5e-4167-96de-8339d1344f51/main.min.js 462 KiB [emitted] (name: main) 1 related asset
runtime modules 727 bytes 4 modules
asset modules 2.21 KiB
modules by path ./maps/ 2.05 KiB 30 modules
modules by path ./assets/ 168 bytes
modules by path ./assets/icons/*.png 84 bytes 2 modules
./assets/icons/cs.svg 42 bytes [built] [code generated]
./assets/map-tools/map-compass.svg 42 bytes [built] [code generated]
javascript modules 404 KiB
modules by path ./src/ 33.6 KiB 16 modules
modules by path ./node_modules/ 351 KiB 6 modules
modules by path ./maps/6-tray-modules/ 19.4 KiB
./maps/6-tray-modules/index.ts 279 bytes [built] [code generated]
./maps/6-tray-modules/world/europe/czechia-tray.module.tsx 19.1 KiB [built] [code generated]
./package.json 1.26 KiB [built] [code generated]

ERROR in C:\Users\me\work\collboard\map\src\modules\map-svg-geojson-import.module.tsx
./src/modules/map-svg-geojson-import.module.tsx 2:4-17
[tsl] ERROR in C:\Users\me\work\collboard\map\src\modules\map-svg-geojson-import.module.tsx(2,5)
TS2724: '"@collboard/modules-sdk"' has no exported member named 'blobToDataUrl'. Did you mean 'blobToDataurl'?
@ ./src/index.ts 13:0-54

webpack 5.35.1 compiled with 1 error in 13994 ms

Error:
at DevelopmentCompiler.<anonymous> (C:\Users\me\work\collboard\map\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:91:37)
at Generator.next (<anonymous>)
at C:\Users\me\work\collboard\map\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:8:71
at new Promise (<anonymous>)
at __awaiter (C:\Users\me\work\collboard\map\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:4:12)
at Watching.handler (C:\Users\me\work\collboard\map\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:85:72)
at C:\Users\me\work\collboard\map\node_modules\webpack\lib\Watching.js:204:9
at Hook.eval [as callAsync] (eval at create (C:\Users\me\work\collboard\map\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\me\work\collboard\map\node_modules\webpack\node_modules\tapable\lib\Hook.js:18:14)
at Watching._done (C:\Users\me\work\collboard\map\node_modules\webpack\lib\Watching.js:201:28)