🚧 Update to SDK 33.0.0
🏭 This commit was automatically generated by generate-modules-sdk script.

Fix of this commit will be marked as:
🤷🏾‍♀️🧝🏽🧎🏻‍♂️⬅️

Full error log:
Error:  asset 2023-1-2--23-0-41--2ea249cf-0927-40a0-b496-401caa3276af/main.min.js 469 KiB [emitted] (name: main) 1 related asset
runtime modules 727 bytes 4 modules
asset modules 2.21 KiB
  modules by path ./maps/ 2.05 KiB 30 modules
  modules by path ./assets/ 168 bytes
    modules by path ./assets/icons/*.png 84 bytes 2 modules
    ./assets/icons/cs.svg 42 bytes [built] [code generated]
    ./assets/map-tools/map-compass.svg 42 bytes [built] [code generated]
javascript modules 411 KiB
  modules by path ./src/ 33.6 KiB 16 modules
  modules by path ./node_modules/ 358 KiB 6 modules
  modules by path ./maps/6-tray-modules/ 19.4 KiB
    ./maps/6-tray-modules/index.ts 279 bytes [built] [code generated]
    ./maps/6-tray-modules/world/europe/czechia-tray.module.tsx 19.1 KiB [built] [code generated]
./package.json 1.24 KiB [built] [code generated]

ERROR in C:\Users\me\work\collboard\map\src\modules\map-switcher.tsx
24:14-27
[tsl] ERROR in C:\Users\me\work\collboard\map\src\modules\map-switcher.tsx(24,15)
      TS2345: Argument of type '{ manifest: { name: string; version: string; description: string; contributors: string[]; license: string; repository: { type: string; url: string; }; title: { en: string; }; categories: string[]; icon: any; flags: { ...; }; }; place: UserInterfaceElementPlace.EdgeRight; createElement(systems: any): Promise<...>; }' is not assignable to parameter of type '{ manifest?: IModuleManifest | undefined; place: UserInterfaceElementPlace; order?: number | undefined; render(systems: ISystems): Promisable<...>; }'.
  Object literal may only specify known properties, and 'createElement' does not exist in type '{ manifest?: IModuleManifest | undefined; place: UserInterfaceElementPlace; order?: number | undefined; render(systems: ISystems): Promisable<...>; }'.

ERROR in C:\Users\me\work\collboard\map\src\modules\map-switcher.tsx
24:28-35
[tsl] ERROR in C:\Users\me\work\collboard\map\src\modules\map-switcher.tsx(24,29)
      TS7006: Parameter 'systems' implicitly has an 'any' type.

webpack 5.35.1 compiled with 2 errors in 13644 ms

Error:
    at DevelopmentCompiler.<anonymous> (C:\Users\me\work\collboard\map\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:91:37)
    at Generator.next (<anonymous>)
    at C:\Users\me\work\collboard\map\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\me\work\collboard\map\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:4:12)
    at Watching.handler (C:\Users\me\work\collboard\map\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:85:72)
    at C:\Users\me\work\collboard\map\node_modules\webpack\lib\Watching.js:204:9
    at Hook.eval [as callAsync] (eval at create (C:\Users\me\work\collboard\map\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\me\work\collboard\map\node_modules\webpack\node_modules\tapable\lib\Hook.js:18:14)
    at Watching._done (C:\Users\me\work\collboard\map\node_modules\webpack\lib\Watching.js:201:28)