🚧 Update to SDK 27.36.0
🏭 This commit was automatically generated by generate-modules-sdk script.

Fix of this commit will be marked as:
🎄🔨🤹‍♀️🆙

Full error log:
Error:  asset 2022-9-14--22-43-32--76403fee-5a82-4e83-aa82-209f8f2f7a57/main.min.js 463 KiB [emitted] (name: main) 1 related asset
runtime modules 727 bytes 4 modules
asset modules 2.21 KiB
modules by path ./maps/ 2.05 KiB 30 modules
modules by path ./assets/ 168 bytes
modules by path ./assets/icons/*.png 84 bytes 2 modules
./assets/icons/cs.svg 42 bytes [built] [code generated]
./assets/map-tools/map-compass.svg 42 bytes [built] [code generated]
javascript modules 405 KiB
modules by path ./src/ 33.6 KiB 16 modules
modules by path ./node_modules/ 352 KiB 6 modules
modules by path ./maps/6-tray-modules/ 19.4 KiB
./maps/6-tray-modules/index.ts 279 bytes [built] [code generated]
./maps/6-tray-modules/world/europe/czechia-tray.module.tsx 19.1 KiB [built] [code generated]
./package.json 1.26 KiB [built] [code generated]

ERROR in C:\Users\me\work\collboard\map\src\modules\map-geojson-art.tsx
17:13-23
[tsl] ERROR in C:\Users\me\work\collboard\map\src\modules\map-geojson-art.tsx(17,14)
TS2515: Non-abstract class 'GeojsonArt' does not implement inherited abstract member 'bottomRight' from class 'Abstract2dArt'.

ERROR in C:\Users\me\work\collboard\map\src\modules\map-geojson-art.tsx
17:13-23
[tsl] ERROR in C:\Users\me\work\collboard\map\src\modules\map-geojson-art.tsx(17,14)
TS2515: Non-abstract class 'GeojsonArt' does not implement inherited abstract member 'topLeft' from class 'Abstract2dArt'.

webpack 5.35.1 compiled with 2 errors in 12862 ms

Error:
at DevelopmentCompiler.<anonymous> (C:\Users\me\work\collboard\map\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:91:37)
at Generator.next (<anonymous>)
at C:\Users\me\work\collboard\map\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:8:71
at new Promise (<anonymous>)
at __awaiter (C:\Users\me\work\collboard\map\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:4:12)
at Watching.handler (C:\Users\me\work\collboard\map\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:85:72)
at C:\Users\me\work\collboard\map\node_modules\webpack\lib\Watching.js:204:9
at Hook.eval [as callAsync] (eval at create (C:\Users\me\work\collboard\map\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\me\work\collboard\map\node_modules\webpack\node_modules\tapable\lib\Hook.js:18:14)
at Watching._done (C:\Users\me\work\collboard\map\node_modules\webpack\lib\Watching.js:201:28)